-- delete exingting tables 
DROP TABLE IF EXISTS Degrees;
DROP TABLE IF EXISTS Prerequisites;
DROP TABLE IF EXISTS Enrollment;
DROP TABLE IF EXISTS Sections;
DROP TABLE IF EXISTS Courses;
DROP TABLE IF EXISTS Minor;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS Departments;
DROP TABLE IF EXISTS Professors;

-- Creating table Professors

CREATE TABLE Professors (
	SSN	INT NOT NULL,
	NAME TEXT NOT NULL,
	TITLE TEXT,
	SEX	TEXT,
	SALARY FLOAT NOT NULL,
	STREET TEXT NOT NULL,
	CITY TEXT NOT NULL,
	ZIP INT NOT NULL,
	STATE TEXT NOT NULL,
	TEL_AREA INT(3) NOT NULL,
	TEL_DIGITS INT(7) NOT NULL,
	PRIMARY KEY (SSN)
);

-- Creating table Departments

CREATE TABLE Departments (
	DNUM INT(5) NOT NULL,
	NAME TEXT NOT NULL,
	D_PHONE NUMERIC(10) NOT NULL,
	LOCATION TEXT NOT NULL,
	CHAIR_SSN INT(9) NOT NULL,
	PRIMARY KEY (DNUM),
	FOREIGN KEY (CHAIR_SSN) REFERENCES Professors (SSN)
);

-- Creating table Courses

CREATE TABLE Courses (
	CNUM INT(5) NOT NULL,
	TITLE TEXT NOT NULL,
	TEXTBOOK TEXT NOT NULL,
	UNITS NUMERIC(4) NOT NULL,
	C_DNUM INT(5) NOT NULL,
	PRIMARY KEY (CNUM),
	FOREIGN KEY (C_DNUM) REFERENCES Departments (DNUM)
);

-- Creating table Students

CREATE TABLE Students (
	CWID INT(8) NOT NULL,
	FNAME TEXT NOT NULL,
	LNAME TEXT NOT NULL,
	S_PHONE NUMERIC(10) NOT NULL,
	S_ADDR TEXT NOT NULL,
	S_DNUM INT(5) NOT NULL,
	PRIMARY KEY (CWID),
	FOREIGN KEY (S_DNUM) REFERENCES Departments (DNUM)
);

-- Creating table Sections

CREATE TABLE Sections (
	SNUM INT(4) NOT NULL,
	CLASSROOM TEXT  NOT NULL,
	SEATS INT  NOT NULL,
	MEETING TEXT  NOT NULL,
	BEGIN_TIME TEXT  NOT NULL,
	END_TIME TEXT  NOT NULL,
	S_CNUM INT(5) NOT NULL,
	S_SSN INT(9) NOT NULL,
	PRIMARY KEY (SNUM),
	FOREIGN KEY (S_CNUM) REFERENCES Courses (CNUM),
	FOREIGN KEY (S_SSN) REFERENCES Professors (SSN)	
);

-- Creating table Enrollment

CREATE TABLE Enrollment (
	GRADE TEXT NOT NULL,
	E_CWID INT(8) NOT NULL,
	E_SNUM INT(4) NOT NULL,
	FOREIGN KEY (E_CWID) REFERENCES Students (CWID),
	FOREIGN KEY (E_SNUM) REFERENCES Sections (SNUM)
);

-- Creating table Minor

CREATE TABLE Minor (
	M_CWID INT(8) NOT NULL,
	M_DNUM INT(5) NOT NULL,
	FOREIGN KEY (M_CWID) REFERENCES Students (CWID),
	FOREIGN KEY (M_DNUM) REFERENCES Departments (DNUM)
);

-- Creating table Prerequisite courses

CREATE TABLE Prerequisites (
	P_CNUM INT(5) NOT NULL,
	PRE TEXT NOT NULL,
	FOREIGN KEY (P_CNUM) REFERENCES Courses (CNUM)
);

-- Creating table Degrees

CREATE TABLE Degrees (
	D_SSN INT(9) NOT NULL,
	DEGREE TEXT NOT NULL,
	FOREIGN KEY (D_SSN) REFERENCES Professors (SSN)
);